import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";
// import SWRProviders from "../../swr-provider";
import { Header } from "@/components/header";
import localFont from "next/font/local";
import { Footer } from "@/components/footer";

const LPMQ = localFont({
  src: "../../../font/LPMQ.ttf",
  display: "swap",
  variable: "--font-LPMQ",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
//   children,
  surahDetail,
}: {
//   children: React.ReactNode;
  surahDetail: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${LPMQ.variable} bg-zinc-100`}>
          <Header />
          <main className="mx-auto max-w-screen-lg space-y-0 px-3">
            {/* {children} */}
            {surahDetail}
          </main>
          <Footer />
      </body>
    </html>
  );
}
